In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import itertools
import pathlib
import os

In [24]:
df = pd.read_csv(str(pathlib.Path("GSE134896_FSKrepExpTable.csv")))
#df = df.drop('Gene_Name', 1)

In [3]:
default_groups = [
    ['CTRL_0', 'CTRL_1', 'CTRL_2'],
    ['P4_0', 'P4_1', 'P4_2'],
    ['IL1B_0', 'IL1B_1', 'IL1B_2'],
    ['FSK_0', 'FSK_1', 'FSK_2'],
    ['FSK_P4_0', 'FSK_P4_1', 'FSK_P4_2'],
    ['P4_IL1B_0', 'P4_IL1B_1', 'P4_IL1B_2'],
    ['FSK_IL1B_0','FSK_IL1B_1', 'FSK_IL1B_2',],
    ['FSK_P4_IL1B_0', 'FSK_P4_IL1B_1','FSK_P4_IL1B_2']
]

In [4]:
def differentially_expressed_genes_t_test(row, x_column_list, y_column_list):
    x_distribution = list(row[x_column_list])
    y_distribution = list(row[y_column_list])

    t_statistic, p_value = stats.ttest_ind(x_distribution, y_distribution)

    return abs(t_statistic)

In [5]:

def differentially_expressed_genes_difference(row):

    difference = abs(row['final_x_values'] - row['final_y_values']) 

    return difference

In [ ]:
for i in range(len(df.columnns))

In [13]:
all_combos = itertools.combinations(df.columns, len(df.columns))

In [107]:
all_combos = []

for L in range(2, 4):
    for subset in itertools.combinations(df.columns, L):
        current_subset = list(subset)
        current_subset.sort()
        #print(current_subset)
        
        all_combos.append(current_subset)

In [7]:
results = []
a = ['CTRL_0', 'P4_1']
b =  ['IL1B_0', 'FSK_P4_2', 'FSK_P4_1']
for i, row in df.iterrows():
    results.append(differentially_expressed_genes_t_test(row, a, b))

In [8]:
new_df = pd.DataFrame({
    'counter':range(0, len(df)),
    'results':results
})

In [26]:
df[df['Gene_Name'] == 'RNU86']

Gene_Name   CTRL_0   CTRL_1   CTRL_2     P4_0     P4_1     P4_2  \
11916     RNU86  3132.33  12934.7  9309.93  12101.3  7080.37  6130.15   

        IL1B_0   IL1B_1   IL1B_2  ...  FSK_P4_2  P4_IL1B_0  P4_IL1B_1  \
11916  9583.74  10205.1  9719.47  ...   15074.3    6355.85    10479.5   

       P4_IL1B_2  FSK_IL1B_0  FSK_IL1B_1  FSK_IL1B_2  FSK_P4_IL1B_0  \
11916    7832.05     10980.9     24857.1     17080.1        13801.5   

       FSK_P4_IL1B_1  FSK_P4_IL1B_2  
11916        13794.0        11215.3  

[1 rows x 25 columns]

In [11]:
df.std(axis=1)

0         0.834058
1         1.044874
2         0.012334
3         0.919462
4         0.646901
           ...    
16495     0.276776
16496     1.881960
16497    30.629348
16498     1.136061
16499     4.104211
Length: 16500, dtype: float64

In [12]:
df.mean(axis=1)

0          3.134682
1          4.609794
2          0.022322
3          2.125368
4          1.496668
            ...    
16495      2.288187
16496      9.748658
16497    159.030708
16498     11.590671
16499     27.119412
Length: 16500, dtype: float64

In [23]:
(df['CTRL_0'].values).shape

(16500,)

In [50]:
c = np.array([[7, 8], [9, 10],
[11, 12], [13, 14]])
a = np.array([1, 2, 3, 4 ])
a = a[:, np.newaxis]
print(c)
print(a)
(c- a)

[[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
[[1]
 [2]
 [3]
 [4]]


array([[ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])

In [ ]:
n = 5
for i in range(5):
    for j in range(1, 5):
        current_x = all_combos[i]
        current_y = all_combos[j]
        difference_measure = np.array(df.apply(differentially_expressed_genes_t_test, args = [current_x, current_y], axis = 1))
        indices = np.argpartition(-difference_measure, n)[:n]
        temp_df = pd.DataFrame({
            'indices':indices
        })
        current_key = ''.join(current_x) + ''.join(current_y)
        temp_df.to_csv(pathlib.Path('t_test_cache/' + current_key + '.csv'))

In [5]:

file_path = str(pathlib.Path('t_test_cache/CTRL_0CTRL_1CTRL_0P4_1.csv'))
if(os.path.exists(file_path)):
    cache_df = pd.read_csv(file_path)


In [7]:
cache_df['indices']

0    10125
1    13234
2     8161
3    14856
4    10104
Name: indices, dtype: int64